DW/Controllers/DWController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using DW.DocumentHelper;
using DW.Library.Classes;
using DW.Library.DataModels;
using Spire.Xls;

namespace DW.Controllers
{
    public class DWController : Controller
    {
        // GET: DW
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult FetchMonthsYears()
        {
            List<SelectListItem> years = new List<SelectListItem>();
            for (int i = DateTime.Now.Year - 10; i <= DateTime.Now.Year + 10; i++)
            {
                years.Add(new SelectListItem
                {
                    Text = i.ToString(),
                    Value = i.ToString()
                });
            }
            List<SelectListItem> months = new List<SelectListItem>();
            for (int i = 1; i <= 12; i++)
            {
                months.Add(new SelectListItem
                {
                    Text = $"{i} {DateTimeFormatInfo.CurrentInfo?.GetAbbreviatedMonthName(i)}",
                    Value = i.ToString()
                });
            }
            return Json(new { years, months, selectedYear = DateTime.Now.Year, selectedMonth = "" }, JsonRequestBehavior.AllowGet);
        }

        #region full report results
        public ActionResult FullReportResults(int? m, int? y)
        {
            if (m.HasValue)
                ViewBag.SelectedMonth = m.Value;
            if (y.HasValue)
                ViewBag.SelectedYear = y.Value;
            return View();
        }

        public JsonResult FetchFullReportResults(int m, int y)
        {
            var reports = DealerManager.GetFullReport(m, y);
            return Json(reports, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FetchColorsFullReportResults()
        {
            return Json(TableHub.fullReportColors, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region results
        public ActionResult Results(int? m, int? y)
        {
            if (m.HasValue)
                ViewBag.SelectedMonth = m.Value;
            if (y.HasValue)
                ViewBag.SelectedYear = y.Value;
            return View();
        }

        public JsonResult FetchResults(int m, int y)
        {
            var results = ResultManager.GetResults(m, y);
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateResult(long id, string property, string value)
        {
            //save to db
            if (ResultManager.UpdateItem(id, property, value))
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FetchColorsResult()
        {
            return Json(TableHub.resultsColors, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ExportResults(int m, int y)
        {
            string handler = Guid.NewGuid().ToString();
            string monthYear = DateTimeFormatInfo.CurrentInfo?.GetAbbreviatedMonthName(m) + " " + y;

            string title = "2017 DEALERWING NISSAN SERVICE RETENTION PROGRAM";
            string subTitle = DateTimeFormatInfo.CurrentInfo?.GetMonthName(m) + " " + y;
            var results = ResultManager.GetResults(m, y);
            var prevResults = m > 1 ? ResultManager.GetResults(m - 1, y) : ResultManager.GetResults(12, y - 1);
            var tiers = QuarterlyTiersManager.GetQuarterlyTiers(m, y);

            string baseLocation = AppDomain.CurrentDomain.BaseDirectory;
            string appData = baseLocation + @"App_Data\results.xlsx";


            var package = DW.DocumentHelper.Excel.CreateResultsSheet(appData, monthYear, title, subTitle, results, prevResults, tiers);
            string fileName = "Results-" + monthYear + ".xlsx";
            string tempFileLocation = baseLocation + @"App_Data\" + fileName;
            //Results-Sept 2016.xlsx
            FileInfo fi = new FileInfo(tempFileLocation);
            package.SaveAs(fi);

            TempData[handler] = tempFileLocation;

            return Json(new { success = true, fileGuid = handler, fileName = fileName }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult ExportVisits(int m, int y, int id)
        {
            string handler = Guid.NewGuid().ToString();
            string monthYear = DateTimeFormatInfo.CurrentInfo?.GetAbbreviatedMonthName(m) + " " + y;

            var dealer = DealerManager.GetDealer(id, m, y);
            var initialDealer = DealerManager.GetDealerInitial(id);

            string subTitle = DateTimeFormatInfo.CurrentInfo?.GetMonthName(m) + " " + y;

            string baseLocation = AppDomain.CurrentDomain.BaseDirectory;
            string appData = baseLocation + @"App_Data\visits.xlsx";


            var package = DW.DocumentHelper.Excel.CreateVisitsSheet(appData, monthYear, dealer.Name, subTitle, dealer, initialDealer);


            string fileName = "Visits-" + monthYear + ".xlsx";
            string fileNamePdf = "Visits-" + monthYear + ".pdf";
            string tempFileLocation = baseLocation + @"App_Data\" + fileName;
            string tempFileLocationPdf = baseLocation + @"App_Data\" + fileNamePdf;
            //Results-Sept 2016.xlsx
            FileInfo fi = new FileInfo(tempFileLocation);
            package.SaveAs(fi);

            Workbook wb = new Workbook();
            wb.LoadFromFile(tempFileLocation, ExcelVersion.Version2010);
            wb.SaveToFile(tempFileLocationPdf, FileFormat.PDF);


            TempData[handler] = tempFileLocationPdf;

            return Json(new { success = true, fileGuid = handler, fileName = fileNamePdf }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public ActionResult DownloadExcel(string fileGuid, string fileName)
        {
            if (TempData[fileGuid] != null)
            {
                var bytes = System.IO.File.ReadAllBytes(TempData[fileGuid].ToString());
                return File(bytes, "application/vnd.ms-excel", fileName);
            }
            else
            {
                return new EmptyResult();
            }
        }

        [HttpGet]
        public JsonResult ExportPdf(int m, int y, int clientId)
        {
            var curDealer = DealerManager.GetDealer(clientId, m, y);
            var iniDealer = DealerManager.GetDealerInitial(clientId);
            StateVM state;
            if (curDealer.StateID.HasValue)
            {
                state = StateManager.GetState(curDealer.StateID.Value);
            }
            else
            {
                return Json(new { success = false, message= "Dealer State Not Set" }, JsonRequestBehavior.AllowGet);
            }

            string handler = Guid.NewGuid().ToString();
            var tiers = QuarterlyTiersManager.GetQuarterlyTiersForState(m, y, state.Abbreviation);
            bool b;
            using (MemoryStream memoryStream = new MemoryStream())
            {
                b = PDF.GeneratePDF(memoryStream, curDealer, iniDealer, tiers);
                memoryStream.Position = 0;
                TempData[handler] = memoryStream.ToArray();
            }
            if (b)
            {
                return Json(new { success = true, fileGuid = handler, fileName = curDealer.Name + ".pdf" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult DownloadPDF(string fileGuid, string fileName)
        {
            if (TempData[fileGuid] != null)
            {
                byte[] data = TempData[fileGuid] as byte[];
                return File(data, "application/pdf", fileName);
            }
            else
            {
                return new EmptyResult();
            }
        }
        #endregion

        #region report
        public ActionResult Report(int? m, int? y)
        {
            if (m.HasValue)
                ViewBag.SelectedMonth = m.Value;
            if (y.HasValue)
                ViewBag.SelectedYear = y.Value;
            return View();
        }

        public JsonResult FetchReport(int m, int y)
        {
            var reports = ReportManager.GetReports(m, y);
            return Json(reports, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateReport(long id, string property, string value)
        {
            //save to db
            if (ReportManager.UpdateItem(id, property, value))
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FetchColorsReport()
        {
            return Json(TableHub.reportsColors, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

DW/Views/DW/FullReportResults.cshtml
@using DW.Library.Constant
@model IEnumerable<DW.Library.Classes.DealerVM>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Full report results</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <h3>Full Report</h3>
        <div class="form-inline text-center margin-bottom-10">
            <select class="form-control" data-bind="options: years, value: year"></select>
            <select class="form-control"
                    data-bind="options: months,
                       optionsText: 'monthName',
                       optionsValue: 'monthValue',
                       value: month,
                       optionsCaption: 'Select a month...'"></select>
            <button class="btn btn-info btn-sm" data-bind="click: exportResults">Main Report-All Dealers</button>
        </div>
        <table class="table table-bordered table-striped-2n-line">
            <thead>
            <tr>
                <th>Report(s)</th>
                <th class="text-center">Client(s)</th>
                <th class="text-center">Overall</th>
                <th class="text-center">1st Yr</th>
                <th class="text-center">In Warr</th>
                <th class="text-center">Out Warr</th>
                <th class="text-center">CP RO Count vs. Prior Yr</th>
                <th class="text-center">Cust Pay $ vs. Prior Yr</th>
                <th class="text-center">ACB</th>
                <th class="text-center">0 Visit</th>
                <th class="text-center">2+ Visits</th>
                <th class="text-center">Cross</th>

                <th class="text-center"></th>
                <th class="text-center">Overall Retention</th>
                <th class="text-center">4+ Visits</th>
                <th class="text-center">3 Visits</th>
                <th class="text-center">2 Visits</th>
                <th class="text-center">1 Visit</th>
                <th class="text-center">0 Visit</th>
            </tr>
            </thead>
            <tbody data-bind="foreach: clients">
                <tr data-bind="attr: {class: 'fullReport' + clientId}">
                    <td rowspan="2">
                        <button class="btn btn-info btn-sm" title="Retention Result Report"  data-bind="click: function(data, event) { vm.exportPDF(clientId); }"><i class="fa fa-lg fa-file-pdf-o" aria-hidden="true"></i></button>
                        <button class="btn btn-success btn-sm" title="Results By Visit" data-bind="click: function(data, event) { vm.exportReports(clientId); }"><i class="fa fa-lg fa-file-pdf-o" aria-hidden="true"></i></button>
                    </td>
                    <td data-bind="text: clientName" rowspan="2"></td>
                    <td rowspan="2"><input data-bind="percentNumber: result.overall, attr:{'data-property':'fullReport' + clientId}" class="input-cell input-cell-result" /></td>
                    <td rowspan="2"><input data-bind="percentNumber: result.firstYear, attr:{'data-property':'fullReport' + clientId}" class="input-cell input-cell-result" /></td>
                    <td rowspan="2"><input data-bind="percentNumber: result.inWar, attr:{'data-property':'fullReport' + clientId}" class="input-cell input-cell-result" /></td>
                    <td rowspan="2"><input data-bind="percentNumber: result.outWar, attr:{'data-property':'fullReport' + clientId}" class="input-cell input-cell-result" /></td>
                    <td rowspan="2"><input data-bind="percentNumber: result.custPayRo, attr:{'data-property':'fullReport' + clientId}" class="input-cell input-cell-result" /></td>
                    <td rowspan="2"><input data-bind="percentNumber: result.custPayMoney, attr:{'data-property':'fullReport' + clientId}" class="input-cell input-cell-result" /></td>
                    <td rowspan="2"><input data-bind="number: result.abcNow, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td rowspan="2"><input data-bind="number: result.zeroVisitNow, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td rowspan="2"><input data-bind="number: result.twoVisitNow, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td rowspan="2"><input data-bind="number: result.crossNow, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>

                    <td data-bind="text: reportDealer.courtesyText"></td>
                    <td><input data-bind="percentNumber: result.overall, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportDealer.visits4Plus, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportDealer.visits3, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportDealer.visits2, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportDealer.visits1, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportDealer.visits0, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                </tr>
                <tr data-bind="attr: {class: 'fullReport' + clientId}">
                    <td data-bind="text: reportRegional.courtesyText"></td>
                    <td><input data-bind="percentNumber: reportRegional.overallRetention, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportRegional.visits4Plus, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportRegional.visits3, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportRegional.visits2, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportRegional.visits1, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: reportRegional.visits0, attr:{'data-property':'fullReport' + clientId}" class="input-cell" /></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th>Report(s)</th>
                    <th class="text-center">Client(s)</th>
                    <th class="text-center">Overall</th>
                    <th class="text-center">1st Yr</th>
                    <th class="text-center">In Warr</th>
                    <th class="text-center">Out Warr</th>
                    <th class="text-center">CP RO Count vs. Prior Yr</th>
                    <th class="text-center">Cust Pay $ vs. Prior Yr</th>
                    <th class="text-center">ACB</th>
                    <th class="text-center">0 Visit</th>
                    <th class="text-center">2+ Visits</th>
                    <th class="text-center">Cross</th>

                    <th class="text-center"></th>
                    <th class="text-center">Overall Retention</th>
                    <th class="text-center">4+ Visits</th>
                    <th class="text-center">3 Visits</th>
                    <th class="text-center">2 Visits</th>
                    <th class="text-center">1 Visit</th>
                    <th class="text-center">0 Visit</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/scripts/jquery.signalR-2.2.1.js" type="text/javascript"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/scripts/knockout-3.4.0.js" type="text/javascript"></script>
    <script src="~/Scripts/autoNumeric/autoNumeric-min.js"></script>
    <script src="~/Scripts/ViewModels/BaseViewModel.js"></script>
    <script src="~/Scripts/ViewModels/ResultViewModel.js"></script>
    <script src="~/Scripts/ViewModels/ReportViewModel.js"></script>
    <script src="~/Scripts/ViewModels/FullReportResultsModel.js"></script>
    <script>
        var vm;
        $(function () {
            C_BASE.URL.DOWNLOAD_PDF = '@Url.Action("DownloadPDF", "DW")';
            C_BASE.URL.EXPORT_PDF = '@Url.Action("ExportPdf", "DW")';

            C_RESULT.URL.UPDATE_RESULT = '@Url.Action("UpdateResult", "DW")';
            C_REPORT.URL.UPDATE_RESULT = '@Url.Action("UpdateReport", "DW")';

            C_FULL_REPORT_RESULTS.URL.FETCH_COLORS = '@Url.Action("FetchColorsFullReportResults", "DW")';
            C_FULL_REPORT_RESULTS.URL.FETCH_FULL_REPORT_RESULTS = '@Url.Action("FetchFullReportResults", "DW")';
            C_FULL_REPORT_RESULTS.URL.FETCH_MONTHS_YEARS = '@Url.Action("FetchMonthsYears", "DW")';
            C_RESULT.URL.EXPORT_RESULTS = '@Url.Action("ExportResults", "DW")';
            C_RESULT.URL.DOWNLOAD_EXCEL = '@Url.Action("DownloadExcel","DW")';
            C_REPORT.URL.EXPORT_REPORTS = '@Url.Action("ExportVisits", "DW")';
            C_RESULT.ENUM.OVERALL = '@CReport.OverallRetention';
            C_RESULT.ENUM.FIRTS_YEAR = '@CResult.FirstYear';
            C_RESULT.ENUM.IN_WAR = '@CResult.InWar';
            C_RESULT.ENUM.OUT_WAR = '@CResult.OutWar';
            C_RESULT.ENUM.CUST_PAY_RO_VS_PRIOR_YR = '@CResult.CustPayRoVsPriorYr';
            C_RESULT.ENUM.CUST_PAY_MONEY_VS_PRIORT_YR = '@CResult.CustPayMoneyVsPriortYr';
            C_RESULT.ENUM.ABC_NOW = '@CResult.AbcNow';
            C_RESULT.ENUM.ZERO_VISIT_NOW = '@CResult.ZeroVisitNow';
            C_RESULT.ENUM.TWO_VISIT_NOW = '@CResult.TwoVisitNow';
            C_RESULT.ENUM.CROSS_NOW = '@CResult.CrossNow';

            C_REPORT.ENUM.DEALER = '@CCourtesy.Dealer';
            C_REPORT.ENUM.DEALER_STRING = '@CCourtesy.ToString(CCourtesy.Dealer)';
            C_REPORT.ENUM.REGIONAL = '@CCourtesy.Regional';
            C_REPORT.ENUM.REGIONAL_STRING = '@CCourtesy.ToString(CCourtesy.Regional)';

            C_REPORT.ENUM.OVERALL_RETENTION = '@CReport.OverallRetention';
            C_REPORT.ENUM.VISITS4PLUS = '@CReport.Visits4Plus';
            C_REPORT.ENUM.VISITS3 = '@CReport.Visits3';
            C_REPORT.ENUM.VISITS2 = '@CReport.Visits2';
            C_REPORT.ENUM.VISITS1 = '@CReport.Visits1';
            C_REPORT.ENUM.VISITS0 = '@CReport.Visits0';

            vm = new FullReportResultsViewModel();
            vm.init('@ViewBag.SelectedMonth', '@ViewBag.SelectedYear');
            ko.applyBindings(vm);
            vm.fetchColors();
        });
    </script>

</body>
</html>

DW/Views/DW/Index.cshtml
@model dynamic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
    @Html.ActionLink("Reports", "Report", "DW", null , new { @class = "btn" }) <br/>
    @Html.ActionLink("Results", "Results", "DW", null , new { @class = "btn" }) <br />
    @Html.ActionLink("Full Report", "FullReportResults", "DW", null, new { @class = "btn" })
</div>
</body>
</html>

DW/Views/DW/Report.cshtml
@using DW.Library.Constant
@model IEnumerable<DW.Library.Classes.ReportVM>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Report</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <h3>Current Report</h3>
        <div class="form-inline text-center margin-bottom-10">
            <select class="form-control" data-bind="options: years, value: year"></select>
            <select class="form-control"
                    data-bind="options: months,
                       optionsText: 'monthName',
                       optionsValue: 'monthValue',
                       value: month,
                       optionsCaption: 'Select a month...'"></select>
        </div>
        <table class="table table-bordered table-striped-2n-line">
            <thead>
                <tr>
                    <th>Report(s)</th>
                    <th class="text-center" colspan="2">Client(s)</th>
                    <th class="text-center">Overall Retention</th>
                    <th class="text-center">4+ Visits</th>
                    <th class="text-center">3 Visits</th>
                    <th class="text-center">2 Visits</th>
                    <th class="text-center">1 Visit</th>
                    <th class="text-center">0 Visit</th>
                </tr>
            </thead>
            <tbody data-bind="foreach: reports">
                <tr data-bind="attr: {class: 'report' + clientId}">
                    <!-- ko if: $index() % 2 === 0 -->
                    <td rowspan="2"><button class="btn btn-success btn-sm" data-bind="click: function(data, event) { vm.exportReports(clientId); }"><i class="fa fa-lg fa-file-excel-o" aria-hidden="true"></i></button></td>
                    <td data-bind="text: clientName" rowspan="2"></td>
                    <!-- /ko -->
                    <td data-bind="text: courtesyText"></td>
                    <td><input data-bind="percentNumber: overallRetention, attr:{'data-property':'report' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: visits4Plus, attr:{'data-property':'report' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: visits3, attr:{'data-property':'report' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: visits2, attr:{'data-property':'report' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: visits1, attr:{'data-property':'report' + clientId}" class="input-cell" /></td>
                    <td><input data-bind="percentNumber: visits0, attr:{'data-property':'report' + clientId}" class="input-cell" /></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th>Report(s)</th>
                    <th class="text-center" colspan="2">Client(s)</th>
                    <th class="text-center">Overall Retention</th>
                    <th class="text-center">4+ Visits</th>
                    <th class="text-center">3 Visits</th>
                    <th class="text-center">2 Visits</th>
                    <th class="text-center">1 Visit</th>
                    <th class="text-center">0 Visit</th>
                </tr>
            </tfoot>
        </table>
    </div>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/scripts/jquery.signalR-2.2.1.js" type="text/javascript"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/scripts/knockout-3.4.0.js" type="text/javascript"></script>
    <script src="~/Scripts/autoNumeric/autoNumeric-min.js"></script>
    <script src="~/Scripts/ViewModels/BaseViewModel.js"></script>
    <script src="~/Scripts/ViewModels/ReportViewModel.js"></script>
    <script>
        var vm;
        $(function () {
            C_REPORT.URL.UPDATE_RESULT = '@Url.Action("UpdateReport", "DW")';
            C_REPORT.URL.FETCH_COLORS = '@Url.Action("FetchColorsReport", "DW")';
            C_REPORT.URL.FETCH_REPORT = '@Url.Action("FetchReport", "DW")';
            C_REPORT.URL.FETCH_MONTHS_YEARS = '@Url.Action("FetchMonthsYears", "DW")';
            C_REPORT.URL.EXPORT_REPORTS = '@Url.Action("ExportVisits", "DW")';
            C_REPORT.URL.DOWNLOAD_EXCEL = '@Url.Action("DownloadExcel","DW")';

            C_REPORT.ENUM.DEALER = '@CCourtesy.Dealer';
            C_REPORT.ENUM.DEALER_STRING = '@CCourtesy.ToString(CCourtesy.Dealer)';
            C_REPORT.ENUM.REGIONAL = '@CCourtesy.Regional';
            C_REPORT.ENUM.REGIONAL_STRING = '@CCourtesy.ToString(CCourtesy.Regional)';

            C_REPORT.ENUM.OVERALL_RETENTION = '@CReport.OverallRetention';
            C_REPORT.ENUM.VISITS4PLUS = '@CReport.Visits4Plus';
            C_REPORT.ENUM.VISITS3 = '@CReport.Visits3';
            C_REPORT.ENUM.VISITS2 = '@CReport.Visits2';
            C_REPORT.ENUM.VISITS1 = '@CReport.Visits1';
            C_REPORT.ENUM.VISITS0 = '@CReport.Visits0';

            vm = new ReportListViewModel();
            vm.init('@ViewBag.SelectedMonth', '@ViewBag.SelectedYear');
            ko.applyBindings(vm);
            vm.fetchColors();
        });
    </script>
</body>
</html>